
CREATE DATABASE proyectos_uaz;

\c proyectos_uaz;

CREATE TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),    
    priority INTEGER NOT NULL,
    description TEXT,
    deliverydate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    
    name TEXT NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES projects(id)
);

DROP DATABASE proyectos_uaz;

-- registros de proyects

INSERT INTO projects (name, priority, description, deliverydate)
    VALUES('Make a Web App', 1, 'Using Javascript', '2020-05-29');

INSERT INTO projects (name, priority, description, deliverydate)
	VALUES('Make a Api Rest', 1, 'Using node and postgresql', '2020-05-29');
	
INSERT INTO projects (name, priority, description, deliverydate)
	VALUES('Hacer Una Tienda Online', 2, 'Using PHP', '2020-05-29');
	
INSERT INTO projects (name, priority, description, deliverydate)
	VALUES('Make a Chat', 2, 'Using Node and Javascript', '2020-05-29');

INSERT INTO projects (name, priority, description, deliverydate)
	VALUES('Make a CRUD with Django', 1, 'Using Python and Django', '2020-05-29');

-- registros de tasks
INSERT INTO tasks(name, done, projectid) VALUES('Dominar html', true, 1);
INSERT INTO tasks(name, done, projectid) VALUES('Dominar javascript', true, 1);
INSERT INTO tasks(name, done, projectid) VALUES('Dominar css', false, 1);

INSERT INTO tasks(name, done, projectid) VALUES('Dominar node', true, 2);
INSERT INTO tasks(name, done, projectid) VALUES('Aprender javascript', true, 2);
INSERT INTO tasks(name, done, projectid) VALUES('Saber DB en postgresql', true, 2);
INSERT INTO tasks(name, done, projectid) VALUES('Aprender express', false, 2);

INSERT INTO tasks(name, done, projectid) VALUES('Aprender PHP', true, 3);
INSERT INTO tasks(name, done, projectid) VALUES('Aprender Laravel', false, 3);

INSERT INTO tasks(name, done, projectid) VALUES('Aprender node y express', true, 3);
INSERT INTO tasks(name, done, projectid) VALUES('Aprender python y django', true, 3);